src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;
use dsarhoya\DSYFilesBundle\Interfaces\IFileEnabledEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News implements IFileEnabledEntity
{

    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @JMS\Groups({"new_list","new_detail"})
     *
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Type("string")
     * @JMS\SerializedName("title")
     * @JMS\Groups({"new_list","new_detail","r_category_new"})
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotNull
     * @Assert\NotBlank
     * @JMS\SerializedName("body")
     * @JMS\Groups({"new_detail"})
     */
    private $body;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull
     * @JMS\SerializedName("enabled")
     * @JMS\Groups({"new_detail"})
     */
    private $enabled;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="news")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull
     * @JMS\SerializedName("category")
     * @JMS\Groups({"r_new_category"})
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotNull
     * @Assert\NotBlank
     * @JMS\SerializedName("description")
     * @JMS\Groups({"new_detail","r_category_new"})
     *
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     */
    private $img;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     * @Assert\Image(
     *      mimeTypesMessage = "No es una imagen."
     * )
     */
    private $file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getSlug()
    {
        return $this->slug;
    }


    public function setFile($file)
    {
        $this->file = $file;
        $this->setImg(sprintf('news_%s', md5(time())));

        return $this;
    }


    public function getFile()
    {
        return $this->file;
    }

    public function getFileKey()
    {
        return $this->img ? $this->img : null;
    }

    public function getFilePath()
    {
        return 'news';
    }

    public function getFileProperties()
    {
        return ['ACL' => 'public-read'];
    }

    public function getFullPathAndKey()
    {
        return $this->getFilePath().'/'.$this->getImg();
    }

}

templates/principal_view/_formUser.html.twig
{{ form_start(loginForm) }}
    {{ form_row(loginForm.email)}}
    {{ form_row(loginForm.user)}}
    {{ form_row(loginForm.password)}}

<button class="btn btn-primary mb-5" type="submit">{{ button_text }}</button>
{{ form_end(loginForm)}}

templates/principal_view/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Noticias Principal{% endblock %}



{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('css/blog-home.css') }}">
{% endblock %}




{% block body %}
{{ parent() }}


  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">¡Noticias Practica!

        </h1>

        {% for new in news %}
          <div class="card mb-4">

            {# Only during development #}
            {% if fileUrl(new.fullPathAndKey) matches '/lorempixel/' %}
              <img  src="{{ new.img }}" width="auto" height="auto">
              {% else %}
                <img src="{{ fileUrl(new.fullPathAndKey) }}" alt="">
            {% endif %}

            <div class="card-body">
              <h2 class="card-title"><a href="{{ path('news_page',{slug:new.slug}) }}">{{ new.title }}</a></h2>
              <p class="card-text">{{new.description}}</p>

            </div>
            <div class="card-footer text-muted">
              <p class="font-weight-bold mb-0">Categoria: {{ new.category }}</p>
              <p class="font-weight-lighter">Creada en: {{ new.createdAt|date('d/m/Y H:m:s') }}</p>



            </div>
          </div>
      {% endfor %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Buscar Noticia</h5>
          <div class="card-body">
            <div class="input-group">
              <form action="{{ path('news_index') }}" method="GET">
                <div class="row">
                <input type="text" class="form-control col-7 ml-2" placeholder="Nombre de noticia" name="name">
                  <button class="btn btn-secondary ml-1" type="submit">Buscar</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categorias</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  {% for category in categories %}
                  <li>
                    <a href="{{ path('category_news',{name:category}) }}">{{ category }}</a>
                  </li>

                  {% endfor %}
                </ul>
              </div>

            </div>
          </div>
        </div>



      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->


{% endblock %}


{% block javascripts %}
  <script src="{{ asset('js/gulpfile.js') }}"></script>
{% endblock %}

templates/principal_view/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PrincipalViewController!{% endblock %}



{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/login.css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/blog-home.css') }}">



{% endblock %}

{% block body %}
    {{ parent() }}

    <div class="container w-25 mb-5 rounded mt-3">
    <h2>Registrarse</h2>
        {{ form_start(userForm) }}
            {{ form_widget(userForm) }}
        <button type="submit">Registrarse</button>
        {{ form_end(userForm) }}

    </div>

{% endblock %}


{% block javascripts %}
    <script src="{{ asset('js/gulpfile.js') }}"></script>
{% endblock %}